### PR TITLE
Add some hotkeys

### PR DESCRIPTION
**Pull request by ifitzpatrick**
Adds hotkeys for deleting, focusing on a selected element, and framing the whole graph. Would like to make this more configurable in the future. This pr also includes a WeakMap polyfill to the-graph-editor/index.html (used in webcomponents.js) that makes it easier to test on older browsers.

### CODE REVIEW

**Comment by forresto** [comment]
The hotkey code looks good, but I don't see where `WeakMap` is used to need the polyfill?

**Comment by ifitzpatrick** [comment]
It's used in webcomponents.js. I can leave that out if you want but I couldn't run index.html on my version of chrome without it.

**Comment by ifitzpatrick** [comment]
In addition to these hotkeys I also want to add some hotkeys to noflo-ui to open up the component library and select stuff in there. It feels a little weird to have two separate sets of hotkeys. Maybe I should just expose this functionality to noflo-ui and set up the all hotkeys there?

**Comment by ifitzpatrick** [comment]
Reopening off of hotkeys branch so I can use master for development

**Pull request closed without merging**
